steps:
  # Étape 1 : Installation système + Vectorisation
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 1. On installe les compilateurs C++ obligatoires pour ChromaDB
        apt-get update && apt-get install -y build-essential git
        
        # 2. On installe les librairies Python
        pip install --upgrade pip
        pip install -r requirements.txt
        
        # 3. DEBUG : On affiche la liste des fichiers pour être sûr que build_db.py est là
        echo "📂 Liste des fichiers présents :"
        ls -la
        
        # 4. Lancement du script (On utilise bien build_db.py comme vu dans ton ancien fichier)
        echo "🚀 Lancement de la vectorisation..."
        python build_db.py
    env:
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}'

  # Étape 2 : Construction de l'image Docker (avec la base chroma_db incluse)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/socialpro2026', '.']

  # Étape 3 : Envoi de l'image vers Google Cloud
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/socialpro2026']

images:
  - 'gcr.io/$PROJECT_ID/socialpro2026'