steps:
  # Étape 1 : On installe tout et on lance TA vectorisation
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        # On utilise ton script existant
        python build_db.py
    env:
      # On passe ta clé API pour que Gemini puisse lire les textes
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}'

  # Étape 2 : On construit l'image Docker avec la nouvelle base chroma_db incluse
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/socialpro2026', '.']

  # Étape 3 : On stocke cette image prête à l'emploi chez Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/socialpro2026']

images:
  - 'gcr.io/$PROJECT_ID/socialpro2026'