steps:
  # Étape 0 : Installation et Vectorisation
  - name: 'python:3.10-slim'
    id: 'vectorize'
    script: |
      apt-get update && apt-get install -y build-essential git
      pip install --upgrade pip
      pip install -r requirements.txt
      python build_db.py
    env:
      - 'GOOGLE_API_KEY=${_API_KEY}'

  # Étape 1 : Sauvegarde de la DB sur Cloud Storage
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'upload-db'
    script: |
      gsutil cp chroma_db/chroma.sqlite3 gs://social2026-data/chroma.sqlite3

timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _API_KEY: 'default_value' # Sera remplacé par la commande