[theme]
base = "light"
primaryColor = "#1E3A8A"        # Bleu Nuit (Boutons, etc.)
backgroundColor = "#FFFFFF"     # Blanc Pur (Fond page)
secondaryBackgroundColor = "#F0F2F6" # GRIS CLAIR (Fond des inputs et widgets) <- C'est ici qu'on change !
textColor = "#1E3A8A"           # Bleu Nuit (Texte)
font = "sans serif"